package data;
// Generated 18/04/2017 21:36:03 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Room generated by hbm2java
 */
public class Room  implements java.io.Serializable {


     private Integer number;
     private String description;
     private byte situation;
     private Date bookDate;
     private Date enterDate;
     private Date exitDate;
     private float dailyAmount;
     private Set clients = new HashSet(0);

    public Room() {
    }

	
    public Room(String description, byte situation, float dailyAmount) {
        this.description = description;
        this.situation = situation;
        this.dailyAmount = dailyAmount;
    }
    public Room(String description, byte situation, Date bookDate, Date enterDate, Date exitDate, float dailyAmount, Set clients) {
       this.description = description;
       this.situation = situation;
       this.bookDate = bookDate;
       this.enterDate = enterDate;
       this.exitDate = exitDate;
       this.dailyAmount = dailyAmount;
       this.clients = clients;
    }
   
    public Integer getNumber() {
        return this.number;
    }
    
    public void setNumber(Integer number) {
        this.number = number;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public byte getSituation() {
        return this.situation;
    }
    
    public void setSituation(byte situation) {
        this.situation = situation;
    }
    public Date getBookDate() {
        return this.bookDate;
    }
    
    public void setBookDate(Date bookDate) {
        this.bookDate = bookDate;
    }
    public Date getEnterDate() {
        return this.enterDate;
    }
    
    public void setEnterDate(Date enterDate) {
        this.enterDate = enterDate;
    }
    public Date getExitDate() {
        return this.exitDate;
    }
    
    public void setExitDate(Date exitDate) {
        this.exitDate = exitDate;
    }
    public float getDailyAmount() {
        return this.dailyAmount;
    }
    
    public void setDailyAmount(float dailyAmount) {
        this.dailyAmount = dailyAmount;
    }
    public Set getClients() {
        return this.clients;
    }
    
    public void setClients(Set clients) {
        this.clients = clients;
    }




}


